### ISSUE TITLE
circular import in backend

### ISSUE THREAD

**Issue by cvraut** [borntonguyen/Gruntled#101]
https://github.com/borntonguyen/Gruntled/blob/dfc3eeacd10cf745341c7f103272347d76d953f9/models.py#L2
https://github.com/borntonguyen/Gruntled/blob/dfc3eeacd10cf745341c7f103272347d76d953f9/init.py#L20

**Comment by leepriscilla** [comment]
template: https://github.com/do-community/flask_auth_scotch

**Comment by leepriscilla** [comment]
![image](https://user-images.githubusercontent.com/33838287/176956794-56eae16c-3edb-4654-8234-03a12579e1bd.png)

**Comment by cvraut** [comment]
ok finally got this issue resolved & deployed to g☁
https://github.com/borntonguyen/Gruntled/commit/b7f7275e5ee27d87df9728e3ce5be3db6d44147a
https://github.com/borntonguyen/Gruntled/commit/e56dc288bc6675b3c59c63625ee81ce391412978

These 2 commits highlight the main deployment issues.

Main points:
 - database initialization was missing
 - tutorial had some name conflicts with the HTML templates, so I fixed those as well
 - backend is organized as a pkg now
The pkg can be run via `python -m gruntled_backend` , but the backend should be tested via `python main.py` as that's how gcloud does it
