### ISSUE TITLE
rename google cloud server from 'project 'to 'Gruntled-Backend'

### ISSUE THREAD

**Issue by borntonguyen** [borntonguyen/Gruntled#77]

**Comment by cvraut** [comment]
created new project at https://console.cloud.google.com/apis/credentials?cloudshell=true&project=gruntled-backend

**Comment by cvraut** [comment]
created the oath2 credentials & stored them locally, need to create an endpoint to test encrypting & uploading them to the github

**Comment by cvraut** [comment]
closing issue for now
