### ISSUE TITLE
Research Flask Login Examples

### ISSUE THREAD

**Issue by borntonguyen** [borntonguyen/Gruntled#85]
https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login

**Comment by cvraut** [comment]
@leepriscilla  is currently following [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login)

@cvraut updated the notes & added environment.yml via 5f1a7cdc8285ca42d1c2b232b41a8a57c3b0a1d6

**Comment by cvraut** [comment]
I think we are done with research & working on legit implementation rn.

Closing until it needs to be reopened again
