### ISSUE TITLE
Compare & Contrast restrictional limits for python bits (Google Cloud vs. Youtube API)

### ISSUE THREAD

**Issue by borntonguyen** [borntonguyen/Gruntled#97]

**Comment by cvraut** [comment]
using the python script I had uploaded previously we hit the daily quota right quick, 6 videos just like the documentation says for the youtube API:

![image](https://user-images.githubusercontent.com/10603882/176503438-537b17b4-df94-4230-b351-ab6565f907d4.png)

**Comment by cvraut** [comment]
note, I can still manually upload a vid, so selenium seems like a viable solution

![image](https://user-images.githubusercontent.com/10603882/176504304-ac080d0e-a48f-4803-abc6-e9fe99686112.png)
